### ISSUE TITLE
hey-pane looses pane information when closing atom

### ISSUE THREAD

**Issue by oniter** [timomeh/hey-pane#21]
First. Really useful tool and THX for sharing it.

When I'm in hey-pane mode and close atom, the same view is present when reopen atom.
But using my keyboard-shortcut for hey-pane doesn't change back to the default view. 
So I need to reorganize that view.

Solution till now is only to leave hey-pane mode before closing atom, but I forgot that quite often.

**Comment by timomeh** [comment]
Thanks for your request!

In fact, when you toggle focus of a pane using hey-pane, it simply toggles a css classname on the active pane. If you close the window, Atom will save the sizes of the panes, but won't save this classname. That's why the pane is still expanded if you re-open your window, but hey-pane doesn't know that.

So hey-pane would need to store which pane is currently active, and when atom re-opens, it should try to set focus of this pane. "hydrate" its state.

This should be a nice issue to contribute. If you – or anyone else reading this – wants to add this feature, go ahead and grab it!

**Comment by oniter** [comment]
All suddenly it is now working like a charm ;-)

At the beginning I could reproduce the described "misbehavior".
After installing some other packages, it is now working like expected.

Unfortunately I didn't recognize which package (maybe) is solving the issue.
Closest candidates are Zen, expose, minimap.

So for me it is solved. Thx.
